name = input("Hello! What is your name?")
age = input("How old are you?")
city = input("What city do you live in?")
college = input("What college do you go to?")
profession = input("What is your profession?")
animal = input("What type of animal do you have?")
petname = input("What is your pets name?")
print("There once was a person named",name,"who lived in",city,". At the age of",age,",",name,"went to college at",college,".",name,"graduated and went to work as a",profession,". Then,",name,"adopted a(n)",animal,"named",petname,". They both lived happily ever after!")
